name: NodeJS with Webpack

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Check out the latest code from the repository

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'  # Automatically caches npm dependencies

      - name: Install project-specific dependencies
        run: |
          npm install @angular/cli@^18.0.0 --save-dev  
          npm install @angular-devkit/build-angular@^18.0.0 --save-dev 
          npm install  # Install all other project dependencies

      - name: Install Angular CLI globally
        run: npm install -g @angular/cli@^18.0.0  # Optional: Install Angular CLI globally if needed

      - name: Build the project with Angular CLI
        run: npx ng build --configuration development --verbose  # Use npx to run the locally installed Angular CLI

    # Uncomment below section if Webpack is used for manual bundling
    # - name: Build the project with Webpack
    #   run: npx webpack --mode development  # Run webpack using npx to bundle the application

    # Moving Forward: Add steps for additional commands, such as testing or deployment
