name: NodeJS with Webpack

on:
  push:
    branches: [ main ]  # Simplified syntax for single-item arrays
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Check out the latest code from the repository

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'  # This option automatically caches npm dependencies and replaces the separate cache step

      - name: Install dependencies
        run: npm install  # Install all project dependencies

      - name: Install Angular CLI globally
        run: npm install -g @angular/cli@^18.0.0  # Install Angular CLI matching project version

      - name: Ensure @angular-devkit/build-angular is installed
        run: npm install --save-dev @angular-devkit/build-angular@^18.0.0  # Ensure necessary devkit is installed

      - name: Build the project with Angular CLI
        run: ng build --configuration development --verbose  # Use verbose logging for better debugging info

    # Uncomment below section if Webpack is used for manual bundling
    # - name: Build the project with Webpack
    #   run: npx webpack --mode development  # Run webpack using npx to bundle the application

    # Moving Forward: Add steps for additional commands, such as testing or deployment
